### ISSUE TITLE
expected primary-expression before '}' token

### ISSUE THREAD

**Issue by planorayhill** [MORA99/particle-ds18x20#1]
Veryfing code using this library in Particle Build fails with this error:

```
ds18x20/onewire.cpp:119:2: error: expected primary-expression before '}' token
  }
  ^
```

**Comment by MORA99** [comment]
Thanks, I have fixed it and reimported the lib as 0.0.3

**Comment by planorayhill** [comment]
Is your updated lib 0.0.3 "automatically" accessible in Particle's  WEB IDE Community Libraries or do I need to do something via GitHub to access 0.0.3?

**Comment by MORA99** [comment]
You need to go to settings -> clear cache on particle build.
Then remove the lib from your project and readd it, that should give you 0.0.3

**Comment by planorayhill** [comment]
I removed the DS18X20 lib from my app.  I cleared cache and refreshed libraries, I still see only DS18X20 0.0.2.  I went ahead added the visible DS18X20 lib to my app.  On compile, I still get the onewire.cpp error i reported yesterday.  I can't figure out what I'm doing wrong.

**Comment by MORA99** [comment]
If you go to library list and find it, then click info icon next to the name, do you get a popup where you can select version ?

**Comment by planorayhill** [comment]
No popup.  If I click DS18X20, I only see 0.0.2 listed.

**Comment by MORA99** [comment]
oops, can you try now, may need to clear cache again.

I forgot to click publish

**Comment by planorayhill** [comment]
Got it (0.0.3)  Thanks, I'll include it in my my app, compile and most likely I'll get back with a Solved.  Thanks again.

**Comment by planorayhill** [comment]
Looks Good.  Is there a specific way to close issues on github?

**Comment by MORA99** [comment]
Great, bit of a learning experience this web ide.
The issue is already closed :)
